# Generated by Django 2.1.7 on 2019-03-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20190303_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='type',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.WordType'),
        ),
    ]
